[[main]]
  name = "Publications"
  url = "/publication/"
  weight = 10

[[main]]
  name = "Talks"
  url = "/talk/"
  weight = 20

[[main]]
  name = "Teaching"
  url = "/lecture/"
  weight = 30

[[main]]
  name = "Seminar"
  url = "/zemi/"
  weight = 40
