# この言語はトップページのみ。メニューは英語ページへ誘導する。

[[main]]
  name = "Scrīpta"
  url = "/publication/"
  weight = 10

[[main]]
  name = "Acroāsēs"
  url = "/talk/"
  weight = 20

[[main]]
  name = "Doctrīna"
  url = "/lecture/"
  weight = 30

[[main]]
  name = "Schola"
  url = "/zemi/"
  weight = 40
