# この言語はトップページのみ。メニューは英語ページへ誘導する。

[[main]]
  name = "Scripta"
  url = "/publication/"
  weight = 10

[[main]]
  name = "Acroases"
  url = "/talk/"
  weight = 20

[[main]]
  name = "Doctrina"
  url = "/lecture/"
  weight = 30

[[main]]
  name = "Schola"
  url = "/zemi/"
  weight = 40
